services:
  jellyfin:
    image: jellyfin/jellyfin
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    group_add:
      - "27" 
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - type: bind
        source: /mnt/media
        target: /media
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    deploy:
      resources:
        limits:
          memory: 1g
  volumes:
    jellyfin_config:
    jellyfin_cache:
