services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "880:80/tcp"
    environment:
      TZ: "Europe/London"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_misc_etc_dnsmasq_d: "true"
    volumes:
      - pihole_config:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
      - type: bind
        source: ./custom.list
        target: /etc/pihole/custom.list
      - type: bind
        source: ./custom-dns.conf
        target: /etc/dnsmasq.d/02-custom-dns.conf
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped

volumes:
  pihole_config:
  pihole_dnsmasq:
